package com.yashen.d24_hostel.util.enums;

public enum Routes {
    MAINFORM,DASHBOARD,STUDENTMAIN,ROOMMAIN,USERMAIN,RESEVATIONMAIN,

    NEWSTUDENT,UPDATESTUDENT,
    NEWUSER,UPDATEUSER,
    NEWROOM,UPDATEROOM,
    NEWRESEVATION,UPDATERESEVATION
}
